[package]
name = "iroh"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99.16"

[dev-dependencies]
test-case = "1.2.1"
galvanic-assert = "0.8.7"
criterion = "0.4.0"

[[bench]]
name = "evaluate-position"
harness = false
